CREATE TABLE IF NOT EXISTS @PREFIX_locations (
	id INTEGER NOT NULL PRIMARY KEY,
	name TEXT NOT NULL
);

ALTER TABLE @PREFIX_methods ADD COLUMN id_location INTEGER NULL REFERENCES @PREFIX_locations (id) ON DELETE RESTRICT;
ALTER TABLE @PREFIX_sessions ADD COLUMN id_location INTEGER NULL REFERENCES @PREFIX_locations (id) ON DELETE RESTRICT;